/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 * Clase que representa la interfaz gráfica de usuario principal del sistema BioGraph.
 * Permite la interacción del usuario con el programa sin el uso de consola, 
 * facilitando la carga de archivos y la visualización del grafo de interacciones.
 * * @author Daniel Alonso y Génesis Peña
 * @version 1.0
 */
public class Interfaz extends javax.swing.JFrame {
    
    /**
     * Grafo principal del sistema que almacena las interacciones proteicas en memoria.
     */
    private Grafos.Grafo grafoPrincipal = new Grafos.Grafo();
    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        título = new javax.swing.JLabel();
        botonCargarArchivoTXT = new javax.swing.JButton();
        txtProteinaOrigen = new javax.swing.JTextField();
        txtProteinaDestino = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtProteinaEliminar = new javax.swing.JTextField();
        btnEliminarProteina = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarInteraccion = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnDetectarComplejos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReporte = new javax.swing.JTextArea();
        btnCalcularRuta = new javax.swing.JButton();
        btnIdentificarHub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        título.setBackground(new java.awt.Color(0, 0, 0));
        título.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        título.setText("Bienvenido a BioGraph!");
        getContentPane().add(título, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 50));

        botonCargarArchivoTXT.setBackground(new java.awt.Color(0, 0, 0));
        botonCargarArchivoTXT.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        botonCargarArchivoTXT.setForeground(new java.awt.Color(255, 255, 255));
        botonCargarArchivoTXT.setText("Cargar Archivo TXT");
        botonCargarArchivoTXT.addActionListener(this::botonCargarArchivoTXTActionPerformed);
        getContentPane().add(botonCargarArchivoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, 30));

        txtProteinaOrigen.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        getContentPane().add(txtProteinaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 100, -1));

        txtProteinaDestino.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        txtProteinaDestino.addActionListener(this::txtProteinaDestinoActionPerformed);
        getContentPane().add(txtProteinaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 100, -1));

        txtPeso.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, -1));

        txtProteinaEliminar.addActionListener(this::txtProteinaEliminarActionPerformed);
        getContentPane().add(txtProteinaEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 100, -1));

        btnEliminarProteina.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarProteina.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnEliminarProteina.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProteina.setText("Eliminar Proteína");
        btnEliminarProteina.addActionListener(this::btnEliminarProteinaActionPerformed);
        getContentPane().add(btnEliminarProteina, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setText("Proteína Origen:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jLabel2.setText("Proteína Destino:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jLabel3.setText("Peso:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jLabel4.setText("Proteína a eliminar:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        btnAgregarInteraccion.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarInteraccion.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnAgregarInteraccion.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarInteraccion.setText("Agregar Interacción");
        btnAgregarInteraccion.addActionListener(this::btnAgregarInteraccionActionPerformed);
        getContentPane().add(btnAgregarInteraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar en TXT");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        btnVisualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnVisualizar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setText("Visualizar Red de Proteínas");
        btnVisualizar.addActionListener(this::btnVisualizarActionPerformed);
        getContentPane().add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        btnDetectarComplejos.setBackground(new java.awt.Color(0, 0, 0));
        btnDetectarComplejos.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnDetectarComplejos.setForeground(new java.awt.Color(255, 255, 255));
        btnDetectarComplejos.setText("Detectar Complejos Proteicos");
        btnDetectarComplejos.addActionListener(this::btnDetectarComplejosActionPerformed);
        getContentPane().add(btnDetectarComplejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        txtAreaReporte.setColumns(20);
        txtAreaReporte.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        txtAreaReporte.setRows(5);
        jScrollPane1.setViewportView(txtAreaReporte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 500, 150));

        btnCalcularRuta.setBackground(new java.awt.Color(0, 0, 0));
        btnCalcularRuta.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnCalcularRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularRuta.setText("Calcular Ruta Metabólica");
        btnCalcularRuta.addActionListener(this::btnCalcularRutaActionPerformed);
        getContentPane().add(btnCalcularRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        btnIdentificarHub.setBackground(new java.awt.Color(0, 0, 0));
        btnIdentificarHub.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnIdentificarHub.setForeground(new java.awt.Color(255, 255, 255));
        btnIdentificarHub.setText("Identificar Proteína Hub");
        btnIdentificarHub.addActionListener(this::btnIdentificarHubActionPerformed);
        getContentPane().add(btnIdentificarHub, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargarArchivoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarArchivoTXTActionPerformed
    /**
     * Maneja el evento de clic en el botón de cargar archivo.
     * Despliega una advertencia sobre la pérdida de datos no guardados y,
     * tras la confirmación, abre un explorador de archivos para seleccionar
     * el documento con las interacciones proteicas.
     * @param evt El evento de acción generado al presionar el botón.
     */
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Ha guardado los datos actuales? Cargar un nuevo archivo sobrescribirá la información en memoria.",
                "Alerta de Seguridad",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setDialogTitle("Seleccione el archivo de interacciones (.txt o .csv)");

            int seleccion = fileChooser.showOpenDialog(this);

            if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File archivoSeleccionado = fileChooser.getSelectedFile();
                leerDatosDeArchivo(archivoSeleccionado);
            }
        }
        
    }//GEN-LAST:event_botonCargarArchivoTXTActionPerformed

    private void txtProteinaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProteinaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProteinaDestinoActionPerformed

    /**
     * Extrae los datos de los campos de texto, los valida y agrega una nueva 
     * interacción (arista) entre dos proteínas (vértices) en el grafo principal.
     * Muestra alertas informativas sobre el resultado de la operación.
     * * @param evt El evento de acción generado al presionar el botón de agregar.
     */    
    private void btnAgregarInteraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInteraccionActionPerformed
        /** Extraemos el texto que el usuario escribió en los campos */
        String origen = txtProteinaOrigen.getText().trim();
        String destino = txtProteinaDestino.getText().trim();
        String pesoStr = txtPeso.getText().trim();

        /** Validamos que no haya dejado ningún campo vacío */
        if (origen.isEmpty() || destino.isEmpty() || pesoStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, llene todos los campos (Origen, Destino y Peso).",
                    "Campos Incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }

        try {
            /** Convertimos el texto del peso a un número con decimales (Double) */
            double peso = Double.parseDouble(pesoStr);

            /** Le enviamos los datos al grafo principal */
            grafoPrincipal.agregarInteraccion(origen, destino, peso);

            /** Le avisamos al usuario que la operación fue exitosa */
            javax.swing.JOptionPane.showMessageDialog(this,
                    "¡Interacción agregada exitosamente!\n" + origen + " <-> " + destino + " (Peso: " + peso + ")",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            /** Limpiamos los campos de texto para la siguiente entrada */
            txtProteinaOrigen.setText("");
            txtProteinaDestino.setText("");
            txtPeso.setText("");

        } catch (NumberFormatException e) {
            /** Atajamos el error si el usuario no ingresa un número válido en el peso */
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error: El peso debe ser un número válido (ejemplo: 5.5 o 3).",
                    "Error de Formato",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarInteraccionActionPerformed

    /**
     * Extrae el nombre de la proteína del campo de texto y la elimina del grafo 
     * principal, incluyendo todas sus interacciones (aristas) asociadas.
     * Muestra alertas informativas sobre el resultado de la operación.
     * @param evt El evento de acción generado al presionar el botón de eliminar.
     */
    private void btnEliminarProteinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProteinaActionPerformed
        /** Se extrae y limpia el texto ingresado por el usuario */
        String proteinaAEliminar = txtProteinaEliminar.getText().trim();

        /** Se valida que el campo de texto no se encuentre vacío */
        if (proteinaAEliminar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, ingrese el nombre de la proteína que desea eliminar.",
                    "Campo Vacío",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        /** Se verifica la existencia del vértice en el grafo antes de proceder */
        if (grafoPrincipal.buscarVertice(proteinaAEliminar) != null) {
            
            /** Se ejecuta la eliminación de la proteína y sus aristas */
            grafoPrincipal.eliminarProteina(proteinaAEliminar);
            
            /** Se notifica al usuario que la operación fue exitosa */
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La proteína '" + proteinaAEliminar + "' y todas sus interacciones han sido eliminadas.",
                    "Eliminación Exitosa",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            /** Se limpia el campo de texto para futuras operaciones */
            txtProteinaEliminar.setText("");
            
        } else {
            /** Se muestra un mensaje de error si la proteína no existe */
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La proteína '" + proteinaAEliminar + "' no se encuentra en el sistema.",
                    "Proteína No Encontrada",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarProteinaActionPerformed

    private void txtProteinaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProteinaEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProteinaEliminarActionPerformed

    /**
    * Acción del botón para actualizar el repositorio local (archivo TXT).
    *
    * * @param evt Evento del clic
    */   
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
try {
        /** Obtenemos el texto del grafo usando el nombre correcto de tu variable*/
        String textoAGuardar = grafoPrincipal.obtenerContenidoGrafoParaArchivo();
        
        java.io.FileWriter escritor = new java.io.FileWriter("txt.txt"); 
        
        escritor.write(textoAGuardar);
        escritor.close();
        
        javax.swing.JOptionPane.showMessageDialog(this, "¡Archivo actualizado exitosamente!");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
 * Llama al metodo de visualizacion usando el objeto global de Genesis.
 */
    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        grafoPrincipal.mostrarGrafoAnimado();
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnDetectarComplejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetectarComplejosActionPerformed
    txtAreaReporte.setText("");
    
    String resultado = grafoPrincipal.encontrarComplejos();
    
    txtAreaReporte.setText(resultado);
    
    javax.swing.JOptionPane.showMessageDialog(this, "Análisis de complejos finalizado.");
    }//GEN-LAST:event_btnDetectarComplejosActionPerformed

    private void btnCalcularRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRutaActionPerformed
        Algoritmos.Dijkstra motorDijkstra = new Algoritmos.Dijkstra();
    
        String origen = txtProteinaOrigen.getText(); 
        String destino = txtProteinaDestino.getText();
    
        if (origen.isEmpty() || destino.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese origen y destino.");
            return;
        }
        String resultado = motorDijkstra.ejecutarDijkstra(grafoPrincipal, origen, destino);
   
        txtAreaReporte.setText(resultado);
        
    }//GEN-LAST:event_btnCalcularRutaActionPerformed

    private void btnIdentificarHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentificarHubActionPerformed
    Algoritmos.Dijkstra motorAlgoritmos = new Algoritmos.Dijkstra();   
    String resultadoHub = motorAlgoritmos.identificarHub(grafoPrincipal);
    txtAreaReporte.setText("ANÁLISIS DE CENTRALIDAD (HUBS):\n" +
                           "La proteína más esencial es: " + resultadoHub);
    
    javax.swing.JOptionPane.showMessageDialog(this, "La proteína Hub es: " + resultadoHub);
    }//GEN-LAST:event_btnIdentificarHubActionPerformed
    
    /**
     * Lee el archivo de texto plano seleccionado y carga las interacciones proteicas
     * en el grafo principal del sistema. El formato esperado por línea es:
     * Proteina_A, Proteina_B, Costo_Interaccion.
     * * @author Daniel Alonso y Génesis Peña
     * @param archivo El archivo seleccionado por el usuario mediante el JFileChooser.
     */
    private void leerDatosDeArchivo(java.io.File archivo) {
        try {
            java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo));
            String linea;
            grafoPrincipal = new Grafos.Grafo(); 

            while ((linea = br.readLine()) != null) {
                if (linea.trim().isEmpty()) {
                    continue;
                }
                
                String[] partes = linea.split(",");
                if (partes.length == 3) {
                    String proteinaA = partes[0].trim();
                    String proteinaB = partes[1].trim();
                    double peso = Double.parseDouble(partes[2].trim());
                    
                    grafoPrincipal.agregarInteraccion(proteinaA, proteinaB, peso);
                }
            }
            br.close();
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "¡Datos cargados exitosamente! Total de proteínas procesadas: " + grafoPrincipal.getCantidadVertices());

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error al leer el archivo. Verifique el formato.\nDetalle: " + e.getMessage(), 
                    "Error de Lectura", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println("Error al cargar el diseño visual: " + ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarArchivoTXT;
    private javax.swing.JButton btnAgregarInteraccion;
    private javax.swing.JButton btnCalcularRuta;
    private javax.swing.JButton btnDetectarComplejos;
    private javax.swing.JButton btnEliminarProteina;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIdentificarHub;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaReporte;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtProteinaDestino;
    private javax.swing.JTextField txtProteinaEliminar;
    private javax.swing.JTextField txtProteinaOrigen;
    private javax.swing.JLabel título;
    // End of variables declaration//GEN-END:variables
}
